-- Jose Antonio Liebana Delgado

CREATE DATABASE IF NOT EXISTS LSG_Bars DEFAULT CHARACTER SET 'utf8mb4' DEFAULT COLLATE'utf8mb4_general_ci';
USE LSG_Bars;

CREATE TABLE IF NOT EXISTS PERSONA (
    DNI VARCHAR(9) NOT NULL,
    Nom VARCHAR(30) NOT NULL,
    Cognom1 VARCHAR(30) NOT NULL,
    Cognom2 VARCHAR(30) NOT NULL,
    Email VARCHAR(30) UNIQUE NOT NULL,
    PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS LOCALITAT (
    Id_Lloc INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nom_localitat VARCHAR(30),
    Provincia VARCHAR(30),
    Comunitat_autonoma VARCHAR(30),
    Pais VARCHAR(30),
    Continent VARCHAR(30),
    PRIMARY KEY (Id_Lloc)
);

CREATE TABLE IF NOT EXISTS CARREC_EMPLEAT (
    Nom_carrec VARCHAR(30) NOT NULL,
    Descripcio VARCHAR(30),
    HoresContracte INT,
    Sou_base DECIMAL,
    PRIMARY KEY (Nom_carrec) 
);

CREATE TABLE IF NOT EXISTS EMPLEAT (
    DNI_Empleat VARCHAR(9) NOT NULL,
    Num_SS VARCHAR(12),
    Num_CC VARCHAR(24),
    Quantitat_sou_extra DECIMAL,
    Nom_carrec VARCHAR(30),
    DNI_cap VARCHAR(9),
    Lloc_naixement int(10) unsigned NOT NULL,
    PRIMARY KEY (DNI_Empleat),
    FOREIGN KEY (DNI_Empleat) REFERENCES Persona (DNI) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Nom_carrec) REFERENCES Carrec_empleat (Nom_carrec) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (DNI_cap) REFERENCES Empleat (DNI_Empleat) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Lloc_naixement) REFERENCES Localitat (Id_Lloc) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS CLIENT (
    DNI_Client VARCHAR(9) NOT NULL,
    Es_Major BOOLEAN,
    PRIMARY KEY (DNI_Client),
    FOREIGN KEY (DNI_Client) REFERENCES Persona (DNI) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS BAR (
    Id_Bar INT NOT NULL AUTO_INCREMENT,
    Nom VARCHAR(30),
    Aforament_maxim INT,
    Te_exterior BOOLEAN,
    Ubicacio int(10) unsigned NOT NULL,
    PRIMARY KEY (Id_Bar),
    FOREIGN KEY (Ubicacio) REFERENCES Localitat (Id_Lloc) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TAULA (
    Numero_taula INT NOT NULL AUTO_INCREMENT,
    Id_Bar INT NOT NULL,
    Es_exterior BOOLEAN,
    Es_fumadors BOOLEAN,
    Num_cadires INT,
    PRIMARY KEY (Numero_taula, Id_Bar),
    FOREIGN KEY (Id_Bar) REFERENCES Bar (Id_Bar) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CLIENT_TAULA (
    Id_client_taula INT NOT NULL AUTO_INCREMENT,
    DNI_Client VARCHAR(9) NOT NULL,
    Numero_Taula INT,
    Id_Bar INT NOT NULL,
    Es_fumador BOOLEAN DEFAULT FALSE,
    Data_hora_arribada DATETIME,
    Data_hora_sortida DATETIME,
    Ha_pagat BOOLEAN,
    PRIMARY KEY (Id_client_taula),
    FOREIGN KEY (DNI_Client) REFERENCES CLIENT (DNI_Client) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Numero_Taula, Id_Bar) REFERENCES TAULA (Numero_Taula, Id_Bar) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE DISTRIBUIDOR(
    Id_Distribuidor INT NOT NULL AUTO_INCREMENT,
    Nom_empresa VARCHAR(30) NOT NULL,
    Contacte_principal VARCHAR(30) NOT NULL,
    Telefon VARCHAR(30) NOT NULL,
    Email VARCHAR(30) NOT NULL UNIQUE,
    Web VARCHAR(30) NOT NULL,
    PRIMARY KEY(Id_Distribuidor)
);

CREATE TABLE TAPA(
    Id_Tapa INT NOT NULL AUTO_INCREMENT,
    Nom VARCHAR(50) NOT NULL,
    Descripcio_carta VARCHAR(50) NOT NULL,
    Temps_preparacio TIME NOT NULL,
    Es_calent BOOLEAN NOT NULL DEFAULT 0,
    Es_vegeta BOOLEAN NOT NULL DEFAULT 0,
    Es_individual BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY(Id_Tapa)
);

CREATE TABLE IF NOT EXISTS BEGUDA (
    Id_Beguda INT NOT NULL AUTO_INCREMENT,
    Nom VARCHAR(50) NOT NULL,
    Descripcio VARCHAR(30),
    Es_calent BOOLEAN NOT NULL DEFAULT 0,
    Te_alcohol BOOLEAN NOT NULL DEFAULT 0,
    Quantitat_CL INT,
    PRIMARY KEY (Id_Beguda)
);

CREATE TABLE IF NOT EXISTS DISTRO_BEGUDA (
    Id_Distribuidor INT NOT NULL,
    Id_Beguda INT NOT NULL,
    Cost_venda DECIMAL(8,2),
    PRIMARY KEY (Id_Distribuidor, Id_Beguda),
    FOREIGN KEY (Id_Distribuidor) REFERENCES DISTRIBUIDOR(Id_Distribuidor) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Id_Beguda) REFERENCES BEGUDA (Id_Beguda) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE  INGREDIENT(
    Id_Ingredient INT NOT NULL AUTO_INCREMENT,
    Nom VARCHAR(30) NOT NULL,
    Descripcio VARCHAR(30) NOT NULL,
    Es_picant BOOLEAN NOT NULL,
    Es_importacio BOOLEAN NOT NULL,
    Cost_gram DECIMAL(8,2) NOT NULL,
    Id_distribuidor INT NOT NULL,
    PRIMARY KEY(Id_Ingredient),
    FOREIGN KEY(Id_Distribuidor) REFERENCES DISTRIBUIDOR(Id_Distribuidor) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE INGREDIENTS_TAPA(
    Id_Ingredient INT NOT NULL AUTO_INCREMENT,
    Id_Tapa INT NOT NULL,
    Quantitat INT NOT NULL,
    PRIMARY KEY(Id_Ingredient,Id_Tapa),
    FOREIGN KEY(Id_Ingredient) REFERENCES INGREDIENT(Id_Ingredient) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(Id_Tapa) REFERENCES TAPA(Id_Tapa) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CARTA_TAPES(
    Id_Tapa INT NOT NULL AUTO_INCREMENT,
    Id_Bar INT NOT NULL,
    Cost DECIMAL(8,2) NOT NULL,
    PVP DECIMAL(8,2) NOT NULL,
    PRIMARY KEY(Id_Tapa, Id_Bar),
    FOREIGN KEY(Id_Tapa) REFERENCES TAPA(Id_Tapa) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(Id_Bar) REFERENCES BAR(Id_Bar) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS CARTA_BEGUDES(
    Id_Beguda INT NOT NULL AUTO_INCREMENT,
    Id_Bar INT NOT NULL,
    Cost DECIMAL NOT NULL,
    PVP DECIMAL NOT NULL,
    PRIMARY KEY (Id_Beguda, Id_Bar),
    FOREIGN KEY (Id_Beguda) REFERENCES BEGUDA(Id_Beguda) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (Id_Bar) REFERENCES BAR(Id_Bar) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS COMANDA_TAPES (
    Id_Tapa INT NOT NULL AUTO_INCREMENT,
    Id_Bar INT NOT NULL,
    Id_client_taula INT NOT NULL,
    Data_hora_comanda DATETIME,
    Quantitat INT,
    PRIMARY KEY (Id_Tapa, Id_Bar, Id_client_taula),
    FOREIGN KEY (Id_Tapa, Id_Bar) REFERENCES CARTA_TAPES (Id_Tapa, Id_Bar) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Id_client_taula) REFERENCES CLIENT_TAULA (Id_client_taula) ON UPDATE CASCADE ON DELETE CASCADE
); 

CREATE TABLE IF NOT EXISTS COMANDA_BEGUDES (
    Id_Beguda INT NOT NULL AUTO_INCREMENT,
    Id_Bar INT NOT NULL,
    Id_client_taula INT NOT NULL,
    Data_hora_comanda DATETIME,
    Quantitat INT,
    PRIMARY KEY (Id_Beguda, Id_Bar, Id_client_taula),
    FOREIGN KEY (Id_Beguda, Id_Bar) REFERENCES CARTA_BEGUDES (Id_Beguda, Id_Bar) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Id_client_taula) REFERENCES CLIENT_TAULA (Id_client_taula) ON UPDATE CASCADE ON DELETE CASCADE
);			